# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: dev

# ConfigMap for custom HTML content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: dev
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to My Website</title>
    </head>
    <body>
      <h1>Hello, welcome to my website!</h1>
      <!-- Add your custom content here -->
    </body>
    </html>

# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-web-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-nginx-app
  template:
    metadata:
      labels:
        app: web-nginx-app
    spec:
      containers:
      - name: web-nginx-app-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html-volume
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: nginx-html-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: dev-web-lb
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: web-nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
